import HOSTS from './hosts.json';
import {drawHost} from './hosts.js';
let hostId='dog';try{hostId=localStorage.getItem('forest-host')||'dog';}catch{}if(!HOSTS.some(h=>h.id===hostId))hostId='dog';
let DOG_PHRASES=HOSTS.find(h=>h.id===hostId).phrases;
const currentHost=()=>HOSTS.find(h=>h.id===hostId);
const sampleKey=i=>hostId==='dog'?'phrase-'+i:hostId+'-phrase-'+i;
import './style.css';
import {COLORS,MOODS,dress,drawStudent,prepareDog,dogPose,drawDog,drawBanana} from './visuals.js';
const $=s=>document.querySelector(s), canvas=$('#canvas'), ctx=canvas.getContext('2d');
const defaults=Array.from({length:6},(_,i)=>'Player '+(i+1));
const artNames=['student-gray','student-green','student-stripes','student-bottle','student-white'];
const descriptions=['Gray shirt + glasses','Dark green shirt','Pink + white stripes','Purple octopus bottle','White shirt + long hair'];
let names=[...defaults];try{const n=JSON.parse(localStorage.getItem('forest-names'));if(Array.isArray(n)&&n.length&&n.length<=30&&n.every(v=>typeof v==='string'))names=n;}catch{}
try{if(!localStorage.getItem('forest-v3-roster')){while(names.length<6)names.push('Player '+(names.length+1));localStorage.setItem('forest-v3-roster','1');localStorage.setItem('forest-names',JSON.stringify(names));}}catch{}
let looks=names.map((_,i)=>({color:i===5?'#4a83d1':null,mood:'auto'}));try{const saved=JSON.parse(localStorage.getItem('forest-looks'));if(Array.isArray(saved))looks=names.map((_,i)=>({...looks[i],...saved[i]}));}catch{}
let rosterBackup=null;try{rosterBackup=JSON.parse(localStorage.getItem('forest-roster-backup'));}catch{}
function backupRoster(){rosterBackup={names:[...names],looks:looks.map(v=>({...v}))};try{localStorage.setItem('forest-roster-backup',JSON.stringify(rosterBackup));}catch{}}
const dressed=new Map(),faces={};let dogParts,action='auto',actionStart=0,manual=[0,0,0,0,0,0],activeAction='rest';
const chosen=[],students=[],bananas=[],art={};let paused=false,gentle=false;
let runAge=0,running=false,ready=false,time=0,last=performance.now(),musicOn=true,voiceOn=true;
const W=1600,H=900,DOG={x:1120,y:188,w:420,h:630},MOUTH={x:1204,y:388};
function random(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}
const lerp=(a,b,t)=>a+(b-a)*t;
function storeNames(){try{localStorage.setItem('forest-names',JSON.stringify(names));localStorage.setItem('forest-looks',JSON.stringify(looks));}catch{}}
function modelIndex(i){const g=looks[i]?.gender;if(g==='boy')return i%2;if(g==='girl')return 2+i%3;return i%5;}
function roster(){const box=$('#roster');box.replaceChildren();names.forEach((name,i)=>{
const row=document.createElement('div');row.className='student'+(chosen.includes(i)?' chosen':'');
const image=document.createElement('img');image.className='avatar';image.src=faces[artNames[modelIndex(i)]]?.[0]?.toDataURL()||'/forest/art/chinese-faces.webp';image.alt=descriptions[modelIndex(i)];
const info=document.createElement('div');info.className='info';const label=document.createElement('label');label.htmlFor='student-name-'+i;label.textContent=`Player ${i+1}`;
const input=document.createElement('input');input.id='student-name-'+i;input.value=name;input.placeholder='Type student name';input.maxLength=30;input.setAttribute('aria-label','Student '+(i+1)+' name');input.addEventListener('input',()=>{names[i]=input.value;storeNames();history();$('#bulk').value=names.join('\n');});input.addEventListener('blur',()=>{if(!names[i].trim()){names[i]='Player '+(i+1);input.value=names[i];storeNames();}});
const choices=document.createElement('div');choices.className='outfit';const color=document.createElement('select');color.setAttribute('aria-label','Player '+(i+1)+' clothing color');for(const [text,value] of COLORS){const opt=new Option(text,value||'original');color.add(opt);}color.value=looks[i]?.color||'original';color.onchange=()=>{looks[i].color=color.value==='original'?null:color.value;storeNames();};
const mood=document.createElement('select');mood.setAttribute('aria-label','Player '+(i+1)+' expression');mood.add(new Option('Changing faces','auto'));MOODS.forEach((name,k)=>mood.add(new Option(name,String(k))));mood.value=looks[i]?.mood||'auto';mood.onchange=()=>{looks[i].mood=mood.value;storeNames();};const gender=document.createElement('select');gender.setAttribute('aria-label','Player '+(i+1)+' boy or girl');gender.add(new Option('Boy','boy'));gender.add(new Option('Girl','girl'));gender.value=looks[i]?.gender||(i%5<2?'boy':'girl');gender.onchange=()=>{looks[i].gender=gender.value;storeNames();image.src=faces[artNames[modelIndex(i)]]?.[0]?.toDataURL()||'/forest/art/chinese-faces.webp';image.alt=descriptions[modelIndex(i)];};choices.append(gender,color,mood);
info.append(label,input,choices);const remove=document.createElement('button');remove.className='remove-player';remove.textContent='×';remove.setAttribute('aria-label','Remove player '+(i+1));remove.disabled=names.length===1;remove.onclick=()=>{backupRoster();names.splice(i,1);looks.splice(i,1);storeNames();reset();$('#status').textContent=`Player removed · ${names.length} players ready`;};row.append(image,info,remove);box.append(row);});$('#bulk').value=names.join('\n');$('#player-count').textContent=names.length+' players';$('#add-player').disabled=names.length>=30;$('#undo-roster').hidden=!rosterBackup;}
function resizeRoster(count){if(count<1||count>30)return;backupRoster();while(names.length<count){names.push('Player '+(names.length+1));looks.push({color:COLORS[1+names.length%(COLORS.length-1)][1],mood:'auto'});}names.length=count;looks.length=count;storeNames();reset();$('#status').textContent=count+' players ready.';}
$('#undo-roster').onclick=()=>{if(!rosterBackup)return;const restore=rosterBackup;backupRoster();names=[...restore.names];looks=restore.looks.map(v=>({...v}));storeNames();reset();};
$('#add-player').onclick=()=>resizeRoster(names.length+1);$('#six-players').onclick=()=>resizeRoster(6);
for(const button of document.querySelectorAll('[data-action]'))button.onclick=()=>{action=button.dataset.action;actionStart=time;document.querySelectorAll('[data-action]').forEach(b=>b.setAttribute('aria-pressed',b===button));};
['Left shoulder','Left elbow','Left wrist','Right shoulder','Right elbow','Right wrist'].forEach((name,i)=>{const l=document.createElement('label');l.textContent=name;const input=document.createElement('input');input.type='range';input.min=-180;input.max=180;input.value=0;input.setAttribute('aria-label',name);input.oninput=()=>{manual[i]=Number(input.value)*Math.PI/180;action='manual';document.querySelectorAll('[data-action]').forEach(b=>b.setAttribute('aria-pressed','false'));};l.append(input);$('#joint-sliders').append(l);});
function history(){$('#round-count').textContent=chosen.length+' / '+names.length+' chosen';$('#history').replaceChildren(...chosen.map(i=>{const li=document.createElement('li');li.textContent=names[i];return li;}));$('#empty').hidden=chosen.length>0;}
function setup(){students.length=0;bananas.length=0;names.forEach((_,i)=>{const s={i,progress:0,start:115+(i%3)*130,ground:655+(i%5)*40,base:.82+random()*.36,boost:false,emotion:Math.floor(random()*3),nextEmotion:time+2+random()*3,visible:!chosen.includes(i)};students.push(s);if(s.visible)for(let j=0;j<3;j++)bananas.push({i,p:.35+j*.23,eaten:false});});}
function start(){if(!ready||running)return;names=names.map((n,i)=>n.trim()||'Student '+(i+1));storeNames();unlock();if(chosen.length===names.length)chosen.length=0;setup();runAge=0;paused=false;running=true;$('#pause').disabled=false;$('#pause').textContent='Pause';$('#result').hidden=true;$('#start').disabled=true;$('#start').textContent='Running…';$('#status').textContent=`${names.length-chosen.length} students running toward ${currentHost().name}`;roster();history();}
function reset(){running=false;paused=false;$('#pause').disabled=true;$('#pause').textContent='Pause';chosen.length=0;setup();$('#result').hidden=true;$('#start').disabled=!ready;$('#start').textContent='Start the run →';$('#status').textContent='Everyone is ready for a new round.';$('#announcement').textContent='Class reset';roster();history();}
function select(s){running=false;$('#pause').disabled=true;s.visible=false;chosen.push(s.i);const remain=names.length-chosen.length;$('#winner').textContent=names[s.i];$('#result-sub').textContent=remain?`${remain} ${remain===1?'student is':'students are'} still waiting.`:'Everyone has had a turn!';$('#next').textContent=remain?'Next student →':'Start a new round ↺';$('#result').hidden=false;$('#start').disabled=false;$('#start').textContent=remain?'Next student →':'New round →';$('#status').textContent=`${names[s.i]} has been chosen`;$('#announcement').textContent=names[s.i]+', you have been chosen!';$('#next').focus({preventScroll:true});roster();history();}
$('#start').onclick=start;$('#next').onclick=start;$('#reset').onclick=reset;$('#apply-names').onclick=()=>{const n=$('#bulk').value.split(/\r?\n/).map(v=>v.trim().slice(0,30)).filter(Boolean);if(!n.length){$('#status').textContent='Write at least one name first.';return;}if(n.length>30){$('#status').textContent='Please use up to 30 names.';return;}backupRoster();names=n;looks=names.map((_,i)=>looks[i]||{color:COLORS[1+i%(COLORS.length-1)][1],mood:'auto'});storeNames();reset();$('#status').textContent=`Saved ${names.length} student names.`;};
// Original 96 BPM minor-key dance score, synthesized locally; no remote audio.
let phraseIndex=0,phraseStarted=0,phraseEnds=0,nextPhraseAt=0;
const voiceLoads=new Map(),loadedVoices=new Set();let activeVoice=null,voiceLoading=false;
let audio,master,musicGain,voiceGain,samples={},beatIndex=0,nextBeat=0,audioStarted=false;
const BEAT=60/96,scale=[62,65,69,68,65,62,57,60,62,65,72,69,68,65,60,57];
function tone(freq,t,dur,type,vol,dest=musicGain){const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.009);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(dest);o.start(t);o.stop(t+dur+.02);}
function voice(word,t){if(!voiceOn||!samples[word])return;if(activeVoice){try{activeVoice.stop();}catch{}}const s=audio.createBufferSource();activeVoice=s;s.buffer=samples[word];s.playbackRate.value=.84;s.connect(voiceGain);s.start(t);$('#voice-status').textContent='Speaking: '+currentHost().name;s.onended=()=>{if(activeVoice===s){activeVoice=null;$('#voice-status').textContent=voiceOn?'Character voice ready':'Character voice muted';}};}
function schedule(){if(!audio||audio.state!=='running')return;if(!voiceLoading&&loadedVoices.has(hostId)&&audio.currentTime>=nextPhraseAt){phraseIndex=phraseEnds===0?0:(phraseIndex+1)%DOG_PHRASES.length;phraseStarted=audio.currentTime;const sample=samples[sampleKey(phraseIndex)];phraseEnds=phraseStarted+(sample?sample.duration/.84:5);nextPhraseAt=phraseEnds+1.4;voice(sampleKey(phraseIndex),phraseStarted); }if(nextBeat<audio.currentTime-.4)nextBeat=audio.currentTime+.03;while(nextBeat<audio.currentTime+.15){const b=beatIndex,t=nextBeat;if(musicOn){const midi=scale[b%scale.length];tone(440*2**((midi-69)/12),t,.48,'sine',.17);tone(440*2**((midi+12-69)/12),t+.012,.19,'triangle',.055);if(b%2===0){tone(b%8<4?73.42:65.41,t,.50,'triangle',.22);const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(130,t);o.frequency.exponentialRampToValueAtTime(40,t+.16);g.gain.setValueAtTime(.26,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(musicGain);o.start(t);o.stop(t+.23);}else{tone(180,t,.07,'triangle',.10);tone(2200,t+.31,.045,'square',.012);}if(b%8===0){tone(146.83,t,BEAT*7,'sine',.075);tone(155.56,t,BEAT*7,'sine',.025);}}beatIndex++;nextBeat+=BEAT;}}
async function loadVoice(id){
 if(voiceLoads.has(id))return voiceLoads.get(id);
 const host=HOSTS.find(h=>h.id===id);voiceLoading=true;
 const promise=Promise.all(host.phrases.map(async(_,i)=>{const key=id==='dog'?'phrase-'+i:id+'-phrase-'+i;const r=await fetch('/forest/art/'+key+'.mp3');if(!r.ok)throw new Error('Speech download failed');samples[key]=await audio.decodeAudioData(await r.arrayBuffer());})).then(()=>{loadedVoices.add(id);}).catch(e=>{voiceLoads.delete(id);throw e;}).finally(()=>{voiceLoading=false;});voiceLoads.set(id,promise);return promise;
}
async function unlock(){try{if(!audio){audio=new (window.AudioContext||window['webkitAudioContext'])();master=audio.createGain();musicGain=audio.createGain();voiceGain=audio.createGain();musicGain.gain.value=musicOn?.18:0;voiceGain.gain.value=voiceOn?2.4:0;musicGain.connect(master);voiceGain.connect(master);const limiter=audio.createDynamicsCompressor();limiter.threshold.value=-12;limiter.ratio.value=8;master.connect(limiter);limiter.connect(audio.destination);audio.resume();master.gain.value=Number($('#volume').value)/100;}await audio.resume();await loadVoice(hostId);if(!Object.keys(samples).length)throw new Error('No character voice clips loaded');if(!audioStarted){audioStarted=true;nextBeat=audio.currentTime+.12;nextPhraseAt=audio.currentTime+.12;setInterval(schedule,50);}}catch(e){$('#status').textContent='Sound is unavailable in this browser; the picker still works.';console.error(e);}}
$('#music').onclick=()=>{musicOn=!musicOn;$('#music').textContent=musicOn?'♫ Music on':'♫ Music off';$('#music').setAttribute('aria-pressed',musicOn);if(musicGain)musicGain.gain.setTargetAtTime(musicOn?.18:0,audio.currentTime,.04);if(musicOn)unlock();};$('#voice').onclick=()=>{voiceOn=!voiceOn;$('#voice').textContent=voiceOn?'Character voice on':'Character voice off';$('#voice').setAttribute('aria-pressed',voiceOn);if(voiceGain)voiceGain.gain.setTargetAtTime(voiceOn?2.4:0,audio.currentTime,.04);if(voiceOn){nextPhraseAt=0;unlock();}else{$('#voice-status').textContent='Character voice muted';}};$('#volume').oninput=()=>{if(master)master.gain.setTargetAtTime(Number($('#volume').value)/100,audio.currentTime,.02);};
const hostSelect=$('#host-select');HOSTS.forEach(h=>hostSelect.add(new Option(h.name,h.id)));hostSelect.value=hostId;hostSelect.onchange=async()=>{if(activeVoice){try{activeVoice.stop();}catch{}}hostId=hostSelect.value;try{localStorage.setItem('forest-host',hostId);}catch{}DOG_PHRASES=currentHost().phrases;phraseIndex=0;phraseEnds=0;nextPhraseAt=0;$('#voice-status').textContent=currentHost().name+' ready';if(audioStarted){try{await loadVoice(hostId);nextPhraseAt=0;}catch{$('#voice-status').textContent='Voice could not load. Press Hear character to retry.';}}};
$('#hear-dog').onclick=async()=>{voiceOn=true;$('#voice').textContent='Character voice on';$('#voice').setAttribute('aria-pressed','true');$('#voice-status').textContent='Loading character voice…';await unlock();if(audio?.state==='running'){voiceGain.gain.setValueAtTime(2.4,audio.currentTime);phraseEnds=0;nextPhraseAt=0;schedule();}else{$('#voice-status').textContent='Audio blocked — press Hear character again.';}};
let alarmEnd=0;async function alarm(){if(performance.now()<alarmEnd)return;alarmEnd=performance.now()+1000;$('#red-alert').classList.add('active');setTimeout(()=>$('#red-alert').classList.remove('active'),1000);await unlock();if(!audio)return;const now=audio.currentTime;const g=audio.createGain();g.gain.setValueAtTime(.30,now);g.gain.setValueAtTime(.30,now+.93);g.gain.linearRampToValueAtTime(0,now+1);g.connect(master);const o=audio.createOscillator();o.type='sawtooth';o.frequency.setValueAtTime(480,now);for(let i=1;i<=8;i++)o.frequency.linearRampToValueAtTime(i%2?950:480,now+i*.12);o.connect(g);o.start(now);o.stop(now+1);}
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='x'&&!e.repeat&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();alarm();}});$('#alarm').onclick=alarm;$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
function image(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src;});}
Promise.all([...HOSTS.filter(h=>h.id!=='dog').map(h=>'host-'+h.id),...artNames,'chinese-faces','dog','dog-closed','dog-base-v3','forest'].map(async name=>{const source=await image('/forest/art/'+name+'.webp');if(name.startsWith('host-')){const c=document.createElement('canvas');c.width=512;c.height=768;c.getContext('2d').drawImage(source,0,0,512,768);art[name]=c;}else art[name]=source;})).then(()=>{const masked=document.createElement('canvas');masked.width=art.dog.width;masked.height=art.dog.height;const m=masked.getContext('2d');m.drawImage(art['dog-closed'],0,0,masked.width,masked.height);m.globalCompositeOperation='destination-in';m.drawImage(art.dog,0,0);art['dog-closed']=masked;artNames.forEach((n,row)=>{faces[n]=[0,1,2].map(col=>{const c=document.createElement('canvas');c.width=c.height=360;const a=art['chinese-faces'];c.getContext('2d').drawImage(a,col*a.width/3,row*a.height/5,a.width/3,a.height/5,0,0,360,360);return c;});});roster();dogParts=prepareDog(art);ready=true;$('#loading').remove();$('#start').disabled=false;}).catch(()=>$('#loading').textContent='Artwork could not load. Please refresh.');
new ResizeObserver(()=>{canvas.width=1600;canvas.height=900;}).observe(canvas);
function label(text,x,y,boost){ctx.font='bold 23px Arial';const w=ctx.measureText(text).width+28;ctx.fillStyle=boost?'#f4db69':'#f1efd9';ctx.beginPath();ctx.roundRect(x-w/2,y-30,w,40,9);ctx.fill();ctx.fillStyle='#263c2e';ctx.textAlign='center';ctx.fillText(text,x,y-2);}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;time+=dt;if(!ready)return;if(running&&!paused)runAge+=dt;ctx.clearRect(0,0,W,H);ctx.drawImage(art.forest,0,0,W,H);ctx.fillStyle='#0c19221b';ctx.fillRect(0,0,W,H);
 const clock=audioStarted&&audio?.state==='running'?audio.currentTime:time;const current=audioStarted?phraseIndex:Math.floor(time/7)%DOG_PHRASES.length;const speaking=audioStarted?clock<phraseEnds:true;const open=speaking&&Math.sin(clock*19)>.05;$('#dog-speech').textContent=audioStarted?DOG_PHRASES[current]:'Press Hear character to hear me talk!';activeAction=action==='auto'?['wave','dance','jump','stretch'][Math.floor(time/5)%4]:action;
 const pose=activeAction==='manual'?{jump:0,sway:0,angles:manual}:dogPose(activeAction,time-actionStart);
 if(gentle){pose.jump*=.15;pose.sway*=.3;pose.angles=pose.angles.map(a=>a*.3);}
 const mx=-126,my=-430;MOUTH.x=DOG.x+DOG.w*.5+mx*Math.cos(pose.sway)-my*Math.sin(pose.sway);MOUTH.y=DOG.y+DOG.h-pose.jump+mx*Math.sin(pose.sway)+my*Math.cos(pose.sway);
 if(hostId==='dog')drawDog(ctx,art,dogParts,DOG,pose,open,time);else{const target=drawHost(ctx,art['host-'+hostId],currentHost(),DOG,pose,open,time);MOUTH.x=target.x;MOUTH.y=target.y;}
 for(const b of bananas){const s=students[b.i];if(b.eaten||!s.visible)continue;drawBanana(ctx,lerp(s.start,1204,b.p),s.ground+13,time);}
 const finish=[];const sorted=[...students].sort((a,b)=>a.ground-b.ground);for(const s of sorted){if(!s.visible)continue;if(running&&!paused){const speed=Math.min(135,12+runAge*runAge*1.4);s.progress+=dt*speed*s.base*(s.boost?2:1)/1100;for(const b of bananas){if(b.i===s.i&&!b.eaten&&s.progress>=b.p){b.eaten=true;s.boost=true;}}if(s.progress>=1)finish.push(s);}
 const p=Math.min(s.progress,1),leap=Math.max(0,(p-.85)/.15),shrink=1-leap*.72;const h=248*shrink,w=h*2/3,x=lerp(s.start,MOUTH.x,p),ground=lerp(s.ground,MOUTH.y+h*.48,leap);const bob=running&&!paused?Math.abs(Math.sin(time*(s.boost?17:10)+s.i))*(gentle?8:65)*(1-leap):0;const zigzag=running&&!paused?Math.sin(time*4.5+s.i*2)*(gentle?8:65)*(1-leap):0;ctx.save();ctx.globalAlpha=1-Math.max(0,(leap-.65)/.35);ctx.fillStyle='#07161666';ctx.beginPath();ctx.ellipse(x,s.ground+3,40*shrink,8,0,0,Math.PI*2);ctx.fill();ctx.translate(x,ground-bob+zigzag);ctx.rotate(running&&!paused&&!gentle?Math.sin(time*8+s.i)*.22*(1-leap):0);if(time>s.nextEmotion){s.emotion=(s.emotion+1+Math.floor(random()*2))%3;s.nextEmotion=time+2+random()*3;}const look=looks[s.i]||{color:null,mood:'auto'},model=modelIndex(s.i),key=model+':'+look.color;let body=dressed.get(key);if(!body){body=dress(art[artNames[model]],model,look.color);dressed.set(key,body);}const expression=look.mood==='auto'?s.emotion:Number(look.mood);s.currentExpression=MOODS[expression];drawStudent(ctx,body,faces[artNames[model]][expression],w,h,time+s.i*1.7,running&&!paused,s.boost,gentle);ctx.restore();if(leap<.35)label((names[s.i]||'Student '+(s.i+1))+(s.boost?' 🍌 2×':''),x,ground-bob+zigzag-h-8,s.boost);}
 if(running&&finish.length)select(finish.sort((a,b)=>b.progress-a.progress)[0]);
 // Gentle ambient firefly drift.
 ctx.fillStyle='#e9e99b';for(let i=0;i<12;i++){const x=(i*139+Math.sin(time*.5+i)*22)%1600,y=200+(i*53)%340+Math.sin(time+i)*13;ctx.globalAlpha=.25+.25*Math.sin(time+i);ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
}
roster();history();setup();requestAnimationFrame(frame);
window.forestApp={getState:()=>({ready,running,names:[...names],chosen:[...chosen],activeAction,looks,bananasVisible:bananas.filter(b=>!b.eaten&&students[b.i]?.visible).length,musicOn,voiceOn,audioState:audio?.state,samples:Object.keys(samples),students:students.map(({i,progress,boost,currentExpression})=>({i,progress,boost,currentExpression}))})};


$('#pause').onclick=()=>{if(!running)return;paused=!paused;$('#pause').textContent=paused?'Resume':'Pause';$('#status').textContent=paused?'Race paused.':names.length-chosen.length+' students in the race';};
$('#motion').onchange=()=>{gentle=$('#motion').value==='gentle';};
if(matchMedia('(prefers-reduced-motion: reduce)').matches){gentle=true;$('#motion').value='gentle';}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)$('#pause').click();});
$('#result').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();$('#next').focus();}if(e.key==='Escape'){$('#result').hidden=true;$('#start').focus();}});
