import {useEffect,useRef,useState,type ReactNode} from 'react';
import {abilities,breathDice,clone,modifier,preparedLimit,proficiency,seed,signed,skillAbilities,skillBonus,slots,spellLibrary,validateCharacter,type Character,type Equipment,type Spell} from '../../lib/dnd/character';
import {VAULT_KEY,createVault,encrypt,openVault,parseEnvelope,type Envelope} from '../../lib/dnd/vault';
import {cloudConfigured,readCloud,saveCloud,signIn,signOut,type CloudSession} from '../../lib/dnd/cloud';

const tabs=['Character sheet','Spellbook','Inventory','Journal'] as const;
type Tab=typeof tabs[number];
type LocalSession={key:CryptoKey;salt:string;lastSaved:string};
const err=(e:unknown)=>e instanceof Error?e.message:'Something went wrong. Your saved sheet was not changed.';
const uid=()=>crypto.randomUUID();
function Icon({name,size=20}:{name:string;size?:number}) {
  const paths:Record<string,ReactNode>={
    shield:<><path d="M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7Z"/><path d="M12 7v10M8 11h8"/></>,
    lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>,
    sword:<><path d="m5 3 6 2 9 12-3 3L5 8Z M4 16l5 5M6 18l-3 3M14 18l4-4"/></>,
    book:<><path d="M12 5c-4-3-9-2-9-2v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Z M12 5v16"/></>,
    bag:<><path d="M7 7V5a5 5 0 0 1 10 0v2M4 7h16l1 14H3Z M8 11v2M16 11v2"/></>,
    feather:<><path d="m4 21 9-9M5 17c-2-8 5-15 16-14-1 11-8 18-16 14ZM10 12h6"/></>,
    heart:<path d="M12 21 3.5 12.5C-2 6 6-1 12 6c6-7 14 0 8.5 6.5Z"/>,
    spark:<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>,
    download:<><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.spark}</svg>;
}
function NumberField({label,value,onChange,min=0,max=1000000,disabled=false}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;disabled?:boolean}) {
  return <input aria-label={label} className="cell-input number" type="number" min={min} max={max} disabled={disabled} value={value} onChange={e=>{if(e.target.value!==''){const n=Number(e.target.value);if(Number.isFinite(n)&&n>=min&&n<=max)onChange(n);}}}/>;
}
function Section({eyebrow,title,action,children}:{eyebrow?:string;title:string;action?:ReactNode;children:ReactNode}) {return <section className="sheet-panel"><div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>{children}</section>;}
function downloadFile(name:string,data:unknown) {
  const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);
  const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function BobApp() {
  const [saved,setSaved]=useState<Character>(clone(seed));const [c,setC]=useState<Character>(clone(seed));
  const [tab,setTab]=useState<Tab>('Character sheet');const [editing,setEditing]=useState(false);
  const [local,setLocal]=useState<LocalSession|null>(null);const [cloud,setCloud]=useState<CloudSession|null>(null);
  const [cloudLoading,setCloudLoading]=useState(cloudConfigured);
  const [version,setVersion]=useState(0);const [cloudReady,setCloudReady]=useState(false);const [hasVault,setHasVault]=useState(false);
  const [status,setStatus]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [modal,setModal]=useState<'unlock'|'library'|null>(null);const [authMode,setAuthMode]=useState<'local'|'cloud'>('local');
  const [pendingImport,setPendingImport]=useState<Envelope|null>(null);const [query,setQuery]=useState('');
  const [undo,setUndo]=useState<Character|null>(null);const [roll,setRoll]=useState('');
  const dialog=useRef<HTMLDialogElement>(null);const restoreInput=useRef<HTMLInputElement>(null);
  const dirty=JSON.stringify(c)!==JSON.stringify(saved);const pb=proficiency(c.level);const mod=(a:typeof abilities[number])=>modifier(c.scores[a]);
  const source=local?'Encrypted local notebook':cloudReady?'Cloud character sheet':'Original character sheet';
  useEffect(()=>{
    try{setHasVault(Boolean(localStorage.getItem(VAULT_KEY)));}catch{setError('Browser storage is unavailable. Local saving cannot be used here.');}
    if(cloudConfigured)readCloud().then(r=>{setSaved(r.character);setC(r.character);setVersion(r.version);setCloudReady(true);}).catch(e=>setError(err(e))).finally(()=>setCloudLoading(false));
  },[]);
  useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
  useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
  function change<K extends keyof Character>(key:K,value:Character[K]) {if(editing)setC(v=>({...v,[key]:value}));}
  function startUnlock(mode:'local'|'cloud'='local') {if(cloudLoading){setStatus('Loading the cloud sheet. Please try again in a moment.');return;}setError('');setAuthMode(mode);setModal('unlock');}
  async function authenticate(event:React.FormEvent<HTMLFormElement>) {
    event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const password=String(form.get('password')||'');
    try{
      if(authMode==='cloud') {
        const session=await signIn(String(form.get('email')||''),password);const r=await readCloud();
        if(!dirty){setC(r.character);setSaved(r.character);setVersion(r.version);}setCloud(session);setLocal(null);setCloudReady(true);
      }else{
        const stored=pendingImport||((localStorage.getItem(VAULT_KEY))?parseEnvelope(localStorage.getItem(VAULT_KEY)!):null);
        if(stored) {
          const opened=await openVault(stored,password);
          // Preserve an existing notebook until a restored backup has been decrypted and validated.
          localStorage.setItem(VAULT_KEY,JSON.stringify(stored));setC(opened.character);setSaved(opened.character);setLocal({key:opened.key,salt:opened.salt,lastSaved:JSON.stringify(stored)});
        }else{
          if(password!==form.get('confirm'))throw new Error('The two passwords do not match.');
          const created=await createVault(c,password);localStorage.setItem(VAULT_KEY,JSON.stringify(created.envelope));setLocal({key:created.key,salt:created.salt,lastSaved:JSON.stringify(created.envelope)});setSaved(clone(c));
        }
        setCloud(null);setHasVault(true);setPendingImport(null);
      }
      setEditing(true);setStatus('Editing unlocked. Make changes, then save.');setModal(null);
    }catch(e){setError(err(e));}finally{setBusy(false);}
  }
  async function save() {
    setBusy(true);setError('');
    try {
      const data=validateCharacter(c);
      if(local) {const encrypted=await encrypt(data,local.key,local.salt);if(localStorage.getItem(VAULT_KEY)!==local.lastSaved)throw new Error('Another tab changed this notebook. Export your draft before reloading, so neither version is lost.');const serialized=JSON.stringify(encrypted);localStorage.setItem(VAULT_KEY,serialized);setLocal({...local,lastSaved:serialized});}
      else if(cloud){const r=await saveCloud(data,version,cloud);setVersion(r.version);}
      else throw new Error('Unlock editing before saving.');
      setSaved(clone(data));setEditing(false);setUndo(null);setStatus(local?'Saved and encrypted in this browser. Export a backup to keep another copy.':'Saved to Bob’s cloud sheet.');
    }catch(e){setError(err(e));}finally{setBusy(false);}
  }
  async function lock() {
    if(dirty){setError('Save or discard your changes before locking.');return;}
    if(cloud){try{await signOut(cloud);}catch{setStatus('This device is locked. Cloud session could not be revoked; it will expire automatically.');}}
    setLocal(null);setCloud(null);setEditing(false);setUndo(null);
    if(cloudReady){try{const r=await readCloud();setC(r.character);setSaved(r.character);setVersion(r.version);}catch{setC(clone(seed));setSaved(clone(seed));}}
    else{setC(clone(seed));setSaved(clone(seed));}
    setStatus('Locked. Unlock your notebook to see your saved local changes.');
  }
  async function exportBackup() {
    setError('');try{if(local){downloadFile('Bob-encrypted-backup.json',await encrypt(c,local.key,local.salt));setStatus('Encrypted backup exported. Keep your password to restore it.');}else{downloadFile('Bob-character.json',validateCharacter(c));setStatus('Character JSON exported. This download contains readable character data.');}}catch(e){setError(err(e));}
  }
  async function importBackup(file:File|undefined) {
    if(!file)return;if(dirty){setError('Save or discard your draft before restoring a backup.');return;}
    try{if(file.size>1500000)throw new Error('Backup must be smaller than 1.5 MB.');setPendingImport(parseEnvelope(await file.text()));startUnlock('local');}catch(e){setError(err(e));}
  }
  function rest(kind:'short'|'long') {
    setUndo(clone(c));setC(v=>({...v,...(kind==='long'?{hp:v.maxHp,tempHp:0,deathSuccesses:0,deathFailures:0,slotsUsed:[0,0,0,0,0],hitDice:Math.min(v.level,v.hitDice+Math.max(1,Math.floor(v.level/2)))}:{}),resources:v.resources.map(r=>({...r,remaining:(kind==='long'?/rest/i.test(r.recharge):/short/i.test(r.recharge))?r.max:r.remaining}))}));
    setStatus(kind==='long'?'Long rest applied to this draft: HP, slots, resources, and half your hit dice recovered. Save to keep it.':'Short-rest resources recovered in this draft. Spend hit dice and update HP manually.');
  }
  function rollDie(label:string,bonus=0) {const value=new Uint32Array(1);crypto.getRandomValues(value);const result=1+(value[0]%20);setRoll(`${label}: ${result} ${signed(bonus)} = ${result+bonus}`);}
  const textCell=(key:'name'|'player'|'race'|'characterClass'|'background'|'alignment',label:string)=><label className="identity-cell"><span>{label}</span><input value={c[key]} aria-label={label} readOnly={!editing} maxLength={100} onChange={e=>change(key,e.target.value)}/></label>;
  const numeric=(key:'hp'|'maxHp'|'tempHp'|'ac'|'speed'|'xp'|'hitDice'|'gold',label:string,min=0,max=1000000)=><NumberField label={label} value={c[key]} min={min} max={max} disabled={!editing} onChange={n=>change(key,n)}/>;
  return <div className="dnd-app">
    <header className="topbar"><a href="/" className="brand-link"><span className="brand-icon"><Icon name="shield"/></span><span>SPEAKKAI <span className="brand-separator">/</span> <b>CHARACTER CHRONICLE</b></span></a><div className="top-actions"><span className="view-label"><i className={local||cloud?'dot open':'dot'}/>{editing?'Editing':local||cloud?'Unlocked':'Read only'}</span>{(local||cloud)?<button className="button quiet" onClick={lock} disabled={busy}><Icon name="lock" size={16}/>Lock</button>:<button className="button gold" onClick={()=>startUnlock(cloudReady?'cloud':'local')}><Icon name="lock" size={16}/>Unlock editing</button>}</div></header>
    <main className="app-layout">
      <aside className="character-sidebar">
        <div className="portrait-frame"><img src="/dnd/bob-paladin.webp" width="768" height="1152" alt="Bob, a bronze-scaled dragonborn paladin in chain mail, with an ivory tabard and a greatsword" fetchPriority="high"/><div className="portrait-shade"/><span className="portrait-tag"><Icon name="spark" size={13}/> THE ADVENTURER</span><div className="portrait-caption"><span className="eyebrow">{c.race} · {c.characterClass}</span><h1>{c.name}</h1><p>“I am Bob!”</p></div></div>
        <div className="sidebar-content"><div className="level-row"><span className="level-medal">{c.level}</span><div><span className="eyebrow">LEVEL {c.level}</span><strong>{c.background} · {c.alignment}</strong></div></div><div className="sidebar-rule"/>
        <p className="character-motto">A noble heart.<br/>A very large sword.<br/><em>A tendency to rush in.</em></p>
        <div className="sidebar-facts"><span><Icon name="shield" size={16}/> Fire resistance</span><span><Icon name="sword" size={16}/> Greatsword wielder</span><span><Icon name="book" size={16}/> Fifth edition · 2014 rules</span></div>
        <div className="notebook-note"><span className="eyebrow">YOUR CHRONICLE</span><p>{local?'Your notebook is unlocked on this device. Save changes before locking.':hasVault?'You have an encrypted notebook on this browser. Unlock it to load your saved Bob.':cloudReady?'View Bob’s latest sheet here. Only the owner account can save changes.':'Start a password-protected notebook to keep Bob’s adventures on this device.'}</p><small>{cloudReady?'Cloud saving connected.':'Cloud saving is not connected yet.'}</small></div>
        <button className="sidebar-link" onClick={exportBackup}><Icon name="download" size={16}/>{local?'Export encrypted backup':'Export character JSON'}</button><button className="sidebar-link" onClick={()=>restoreInput.current?.click()} disabled={busy}>↥ Restore encrypted backup</button><input ref={restoreInput} className="hidden-input" type="file" accept=".json,application/json" aria-label="Restore encrypted backup" onChange={e=>{void importBackup(e.target.files?.[0]);e.target.value='';}}/>
        {cloudReady&&!local&&<button className="sidebar-link" onClick={()=>startUnlock('local')}>Open local notebook</button>}
        <small className="portrait-credit">Original character art · generated with ImageGen</small></div>
      </aside>
      <div className="workspace">
        <div className="workspace-heading"><div><span className="eyebrow gold-text">THE ADVENTURE CONTINUES</span><h2>Your legend, in the making.</h2><p>Every stat. Every spell. Every story.</p></div><button className="button quiet desktop-only" onClick={()=>window.print()}>Print this tab ↗</button></div>
        <div className="summary-cards"><div className="summary-stat hp-stat"><Icon name="heart"/><span>HIT POINTS</span><strong>{c.hp}<small> / {c.maxHp}</small></strong><div className="hp-track"><i style={{width:`${Math.min(100,c.hp/c.maxHp*100)}%`}}/></div></div><div className="summary-stat"><Icon name="shield"/><span>ARMOR CLASS</span><strong>{c.ac}</strong><small>Recorded defense</small></div><div className="summary-stat"><Icon name="spark"/><span>INITIATIVE</span><strong>{signed(mod('DEX'))}</strong><small>Dexterity modifier</small></div><div className="summary-stat"><Icon name="feather"/><span>SPEED</span><strong>{c.speed}<small> ft</small></strong><small>Walking speed</small></div></div>
        <nav className="sheet-tabs" aria-label="Character sections">{tabs.map((name,i)=><button key={name} onClick={()=>setTab(name)} aria-current={tab===name?'page':undefined} className={tab===name?'active':''}><Icon name={['shield','book','bag','feather'][i]} size={17}/>{name}</button>)}</nav>
        <div className="sheet-toolbar"><div><span className="source-label">{source}</span><span className="save-state">{dirty?'Unsaved changes':local?'Saved on this device':cloudReady?'Saved in cloud':'June 17, 2026'}</span></div><div className="toolbar-actions">{editing?<><button className="button quiet" disabled={busy} onClick={()=>{setC(clone(saved));setEditing(false);setUndo(null);setError('');setStatus('Draft discarded. Saved sheet restored.');}}>Discard</button><button className="button gold" disabled={busy||!dirty} onClick={save}>{busy?'Saving…':'Save changes'}</button></>:<button className="button outline" onClick={()=>{if(local||cloud)setEditing(true);else startUnlock(cloudReady?'cloud':'local');}}>✎ Edit sheet</button>}</div></div>
        {status&&<p className="notice" role="status">{status}<button aria-label="Dismiss status" onClick={()=>setStatus('')}>×</button></p>}{error&&!modal&&<p className="notice error" role="alert">{error}{cloud&&<button onClick={()=>startUnlock('cloud')}>Sign in again</button>}</p>}
        {tab==='Character sheet'&&<>
          <Section title="Character details" eyebrow="01 / IDENTITY"><div className="identity-grid">{textCell('name','Name')}{textCell('race','Race')}{textCell('characterClass','Class')}<label className="identity-cell"><span>Level</span><NumberField label="Level" value={c.level} min={1} max={20} disabled={!editing} onChange={n=>{if(Number.isInteger(n)){change('level',n);setC(v=>({...v,level:n,hitDice:Math.min(v.hitDice,n),slotsUsed:v.slotsUsed.map((s,i)=>Math.min(s,slots(n)[i]))}));}}}/></label>{textCell('background','Background')}{textCell('alignment','Alignment')}{textCell('player','Player')}<label className="identity-cell"><span>Experience points</span>{numeric('xp','Experience points')}</label><label className="identity-cell"><span>Hit die</span><input aria-label="Hit die" value="d10" readOnly/></label></div></Section>
          <Section title="Abilities & saving throws" eyebrow="02 / THE NUMBERS" action={<span className="small-badge">Proficiency {signed(pb)}</span>}><div className="ability-grid">{abilities.map(a=><div className="ability-card" key={a}><span>{a}</span><strong>{signed(mod(a))}</strong><NumberField label={`${a} score`} value={c.scores[a]} min={1} max={30} disabled={!editing} onChange={n=>change('scores',{...c.scores,[a]:n})}/><label className="save-prof"><input type="checkbox" disabled={!editing} checked={c.proficientSaves.includes(a)} onChange={e=>change('proficientSaves',e.target.checked?[...c.proficientSaves,a]:c.proficientSaves.filter(x=>x!==a))}/><span>Save {signed(mod(a)+(c.proficientSaves.includes(a)?pb:0))}</span></label></div>)}</div><p className="panel-footnote">Modifiers, saves, and skills update automatically. Calculations use single-class 2014 Paladin rules.</p></Section>
          <div className="two-columns"><Section title="Skills" eyebrow="03 / WHAT BOB DOES"><div className="skill-list">{Object.entries(skillAbilities).map(([skill,a])=><label key={skill} className="skill-row"><input type="checkbox" checked={c.proficientSkills.includes(skill)} disabled={!editing} onChange={e=>change('proficientSkills',e.target.checked?[...c.proficientSkills,skill]:c.proficientSkills.filter(s=>s!==skill))}/><span>{skill}</span><small>{a}</small><button title={`Roll ${skill}`} type="button" onClick={()=>rollDie(skill,skillBonus(c,skill))}>{signed(skillBonus(c,skill))}</button></label>)}</div><div className="passive-row"><span>Passive perception</span><strong>{10+skillBonus(c,'Perception')}</strong></div></Section>
          <div className="stack"><Section title="Combat & vitality" eyebrow="04 / STAND YOUR GROUND"><div className="vital-grid">{([['hp','Current HP'],['maxHp','Maximum HP'],['tempHp','Temporary HP'],['ac','Armor class'],['speed','Speed (ft)'],['hitDice','Hit dice left']] as const).map(([k,l])=><label key={k}><span>{l}</span>{numeric(k,l,k==='maxHp'?1:0,k==='hitDice'?c.level:1000000)}</label>)}</div><div className="death-row"><span>Death saves</span>{(['deathSuccesses','deathFailures'] as const).map((k,i)=><label key={k}>{i?'Failures':'Successes'}<NumberField label={i?'Death save failures':'Death save successes'} value={c[k]} min={0} max={3} disabled={!editing} onChange={n=>change(k,n)}/></label>)}</div><label className="inspiration"><input type="checkbox" checked={c.inspiration} disabled={!editing} onChange={e=>change('inspiration',e.target.checked)}/>Inspiration</label><p className="panel-footnote">Hit die: d10. Set maximum HP and feature pools when leveling up.</p></Section>
          <Section title="Attacks" eyebrow="05 / GREAT SWORD, GREAT RESPONSIBILITY"><div className="attack-row"><span className="attack-icon"><Icon name="sword"/></span><div><strong>Greatsword</strong><small>Two-handed · heavy</small></div><div><button className="roll-bonus" onClick={()=>rollDie('Greatsword',mod('STR')+pb)}>{signed(mod('STR')+pb)}</button><small>2d6 {signed(mod('STR'))} slashing</small></div></div><div className="attack-row"><span className="attack-icon"><Icon name="feather"/></span><div><strong>Javelin</strong><small>Range 30 / 120 ft</small></div><div><button className="roll-bonus" onClick={()=>rollDie('Javelin',mod('STR')+pb)}>{signed(mod('STR')+pb)}</button><small>1d6 {signed(mod('STR'))} piercing</small></div></div><div className="attack-row"><span className="attack-icon fire"><Icon name="spark"/></span><div><strong>Fire Breath</strong><small>15 ft cone · Dex save</small></div><div><strong>DC {8+pb+mod('CON')}</strong><small>{breathDice(c.level)}d6 fire</small></div></div><p className="panel-footnote">Click an attack bonus or skill bonus to roll a d20.</p><output className="roll-result" aria-live="polite">{roll||'The dice await.'}</output></Section></div></div>
          <Section title="Features & resources" eyebrow="06 / DIVINE PURPOSE" action={editing?<div className="rest-actions"><button className="button quiet" onClick={()=>rest('short')}>Short rest</button><button className="button outline" onClick={()=>rest('long')}>Long rest</button>{undo&&<button className="button quiet" onClick={()=>{setC(undo);setUndo(null);setStatus('Rest undone.');}}>Undo rest</button>}</div>:undefined}><div className="resource-grid">{c.resources.map((r,i)=><div className="resource-card" key={r.id}><Icon name="spark"/><h3>{r.name}</h3><p>{r.description}</p><div className="resource-counter"><NumberField label={`${r.name} remaining`} value={r.remaining} max={r.max} disabled={!editing} onChange={n=>change('resources',c.resources.map((v,j)=>j===i?{...v,remaining:n}:v))}/><span>/</span><NumberField label={`${r.name} maximum`} value={r.max} max={10000} disabled={!editing} onChange={n=>change('resources',c.resources.map((v,j)=>j===i?{...v,max:n,remaining:Math.min(v.remaining,n)}:v))}/><small>{r.id==='hands'?'points':'uses'}</small></div><span className="recharge">↻ {r.recharge}</span></div>)}</div><div className="feature-strip"><span><strong>Fire resistance</strong>Half damage from fire.</span><span><strong>Position of Privilege</strong>Noble background feature.</span></div></Section>
        </>}
        {tab==='Spellbook'&&<>
          <Section title="The spellbook" eyebrow="DIVINE MAGIC" action={<button className="button outline" onClick={()=>{setQuery('');setModal('library');}}>Browse spells ↗</button>}><div className="spell-summary"><div><span>Spell save DC</span><strong>{c.level<2?'—':8+pb+mod('CHA')}</strong></div><div><span>Spell attack</span><strong>{c.level<2?'—':signed(pb+mod('CHA'))}</strong></div><div><span>Prepared</span><strong>{c.spells.filter(s=>s.prepared).length}<small> / {preparedLimit(c)}</small></strong></div></div><p className="spell-info">{c.level<2?'Bob begins spellcasting at Paladin level 2 under the 2014 rules. Browse spells now and keep a wishlist for the next adventure.':'Prepare spells after a long rest. This is a spell tracker; check components, targets, and full rules with your table.'}</p>{c.spells.filter(s=>s.prepared).length>preparedLimit(c)&&<p className="notice error">More spells are marked prepared than the normal preparation limit. Check oath spells or your DM’s ruling.</p>}</Section>
          <Section title="Spell slots" eyebrow="SPEND WISELY"><div className="slot-grid">{slots(c.level).map((total,i)=><div key={i}><span>LEVEL {i+1}</span><div className="slot-dots">{total?Array.from({length:total},(_,j)=><button key={j} aria-label={`Level ${i+1} slot ${j+1}`} aria-pressed={j<c.slotsUsed[i]} disabled={!editing} className={j<c.slotsUsed[i]?'spent':''} onClick={()=>change('slotsUsed',c.slotsUsed.map((n,k)=>k===i?(j<n?j:j+1):n))}/>):<span>—</span>}</div><small>{total?`${total-c.slotsUsed[i]} of ${total} available`:'Not unlocked'}</small></div>)}</div><p className="panel-footnote">Filled gold slots are available. Click to spend or restore. Long rest restores all slots.</p></Section>
          <Section title="Bob’s spells" eyebrow="PREPARED & COLLECTED" action={editing?<button className="button outline" onClick={()=>change('spells',[...c.spells,{id:uid(),name:'New spell',level:1,casting:'1 action',range:'',duration:'',description:'',prepared:false,concentration:false}])}>+ Custom spell</button>:undefined}>{c.spells.length===0?<div className="empty-state"><Icon name="book" size={34}/><h3>A little room for magic.</h3><p>No spells recorded yet. Explore the library and add your first spell when editing is unlocked.</p><button className="button outline" onClick={()=>setModal('library')}>Explore the spell library</button></div>:<div className="spell-cards">{c.spells.map((s,i)=>{const patch=(value:Partial<Spell>)=>change('spells',c.spells.map((v,j)=>j===i?{...v,...value}:v));return <div className="spell-card" key={s.id}><div className="spell-card-heading"><input aria-label={`Spell ${i+1} name`} className="spell-name" readOnly={!editing} value={s.name} maxLength={200} onChange={e=>patch({name:e.target.value})}/>{editing&&<button className="remove" aria-label={`Remove ${s.name}`} onClick={()=>change('spells',c.spells.filter(v=>v.id!==s.id))}>×</button>}</div><div className="spell-fields"><label>Level<NumberField label={`${s.name} level`} value={s.level} max={9} disabled={!editing} onChange={n=>patch({level:n})}/></label>{(['casting','range','duration'] as const).map(k=><label key={k}>{k}<input readOnly={!editing} aria-label={`${s.name} ${k}`} maxLength={200} value={s[k]} onChange={e=>patch({[k]:e.target.value})}/></label>)}</div><textarea rows={3} aria-label={`${s.name} description`} placeholder="Spell notes and effects…" readOnly={!editing} value={s.description} maxLength={12000} onChange={e=>patch({description:e.target.value})}/><div className="spell-toggles"><label><input type="checkbox" checked={s.prepared} disabled={!editing||c.level<2} onChange={e=>patch({prepared:e.target.checked})}/>Prepared</label><label><input type="checkbox" checked={s.concentration} disabled={!editing} onChange={e=>patch({concentration:e.target.checked})}/>Concentration</label></div></div>;})}</div>}</Section>
        </>}
        {tab==='Inventory'&&<>
          <Section title="Equipment & treasure" eyebrow="WHAT BOB CARRIES" action={editing?<button className="button outline" onClick={()=>change('equipment',[...c.equipment,{id:uid(),name:'New item',quantity:1,weight:0,notes:''}])}>+ Add item</button>:undefined}><div className="inventory-summary"><label>GOLD PIECES {numeric('gold','Gold pieces')}</label><span><strong>{c.equipment.reduce((n,e)=>n+e.quantity*e.weight,0).toLocaleString()} lb</strong> Recorded weight · some items unweighed</span></div><div className="table-scroll"><table className="inventory-table"><thead><tr><th>Item</th><th>Qty</th><th>Lb each</th><th>Notes</th>{editing&&<th><span className="sr-only">Remove</span></th>}</tr></thead><tbody>{c.equipment.map((e,i)=>{const patch=(value:Partial<Equipment>)=>change('equipment',c.equipment.map((v,j)=>j===i?{...v,...value}:v));return <tr key={e.id}><td><input aria-label={`Item ${i+1} name`} readOnly={!editing} maxLength={200} value={e.name} onChange={v=>patch({name:v.target.value})}/></td><td><NumberField label={`${e.name} quantity`} value={e.quantity} max={10000} disabled={!editing} onChange={n=>patch({quantity:n})}/></td><td><NumberField label={`${e.name} weight`} value={e.weight} max={100000} disabled={!editing} onChange={n=>patch({weight:n})}/></td><td><input aria-label={`${e.name} notes`} readOnly={!editing} value={e.notes} maxLength={12000} onChange={v=>patch({notes:v.target.value})}/></td>{editing&&<td><button className="remove" aria-label={`Remove ${e.name}`} onClick={()=>change('equipment',c.equipment.filter(v=>v.id!==e.id))}>×</button></td>}</tr>;})}</tbody></table></div><p className="panel-footnote">Starting gold needs a DM check: the source records 120 gp alongside starting equipment. See Journal. Zero weight means unrecorded.</p></Section>
          <Section title="Training & languages" eyebrow="BEYOND THE BLADE"><div className="journal-grid">{(['languages','proficiencies'] as const).map(k=><label className="journal-field" key={k}><span>{k}</span><textarea aria-label={k} rows={4} readOnly={!editing} maxLength={12000} value={c[k]} onChange={e=>change(k,e.target.value)}/></label>)}</div></Section>
        </>}
        {tab==='Journal'&&<>
          <Section title="The person behind the armor" eyebrow="BOB’S STORY"><div className="journal-grid">{(['traits','ideals','bonds','flaws'] as const).map(k=><label className="journal-field" key={k}><span>{k}</span><textarea aria-label={k} readOnly={!editing} rows={4} value={c[k]} placeholder="A story still to be written…" maxLength={12000} onChange={e=>change(k,e.target.value)}/></label>)}</div></Section>
          <Section title="Adventure notes" eyebrow="THE CHRONICLE"><textarea className="adventure-notes" aria-label="Adventure notes" rows={12} readOnly={!editing} maxLength={12000} value={c.notes} onChange={e=>change('notes',e.target.value)}/><label className="xp-field">Experience points {numeric('xp','Experience points')}</label></Section>
          <Section title="Make it your own" eyebrow="MORE TO THE STORY" action={editing?<button className="button outline" onClick={()=>change('custom',[...c.custom,{id:uid(),label:'New field',value:''}])}>+ Add field</button>:undefined}>{c.custom.length?<div className="custom-fields">{c.custom.map((field,i)=><div key={field.id}><input aria-label={`Custom field ${i+1} label`} readOnly={!editing} value={field.label} maxLength={200} onChange={e=>change('custom',c.custom.map((v,j)=>j===i?{...v,label:e.target.value}:v))}/><textarea aria-label={`Custom field ${i+1} value`} readOnly={!editing} value={field.value} maxLength={12000} onChange={e=>change('custom',c.custom.map((v,j)=>j===i?{...v,value:e.target.value}:v))}/>{editing&&<button className="remove" aria-label={`Remove ${field.label}`} onClick={()=>change('custom',c.custom.filter(v=>v.id!==field.id))}>×</button>}</div>)}</div>:<p className="panel-footnote roomy">Allies, quests, magic items, or a title Bob insists on using. Unlock editing to add your own fields.</p>}</Section>
          <div className="source-note">Source: Bob’s filled character sheet and <a href="https://chatgpt.com/c/6a32aba7-8794-83ee-a07d-7d3b00c77e8d" target="_blank" rel="noreferrer">Starting Equipment Choices ↗</a>, June 17, 2026. Spell summaries are quick reminders, not a full rules reference. Homebrew and later editions may differ.</div>
        </>}
        <footer className="app-footer"><span>BOB’S CHARACTER CHRONICLE</span><span>Built for the next adventure. ✦</span></footer>
      </div>
    </main>
    <dialog ref={dialog} className="dnd-dialog" onCancel={()=>{setModal(null);setPendingImport(null);}} aria-labelledby="dialog-title"><button className="dialog-close" aria-label="Close dialog" disabled={busy} onClick={()=>{setModal(null);setPendingImport(null);}}>×</button>
      {modal==='unlock'?<><span className="modal-emblem"><Icon name="lock" size={28}/></span><span className="eyebrow">THE KEEPER OF THE CHRONICLE</span><h2 id="dialog-title">{authMode==='cloud'?'Sign in to edit Bob':pendingImport?'Restore your notebook':hasVault?'Welcome back, adventurer.':'Start your character notebook.'}</h2><p>{authMode==='cloud'?'Sign in with Bob’s owner account. Saved changes update the public character sheet.':pendingImport?'Enter this backup’s password. Restoring replaces the notebook on this browser; export your current notebook first if you want to keep it.':hasVault?'Enter your notebook password to load and edit your saved character.':'Choose a password for your encrypted notebook. Edits stay on this browser; use encrypted backups to move them to another device. This does not update the public sheet.'}</p><form onSubmit={authenticate} key={`${authMode}-${Boolean(pendingImport)}-${hasVault}`}>
      {authMode==='cloud'&&<label>Email<input autoFocus name="email" type="email" autoComplete="username" required/></label>}
      <label>{authMode==='local'&&!hasVault&&!pendingImport?'Choose password':'Password'}<input autoFocus={authMode==='local'} name="password" type="password" autoComplete={hasVault||pendingImport||authMode==='cloud'?'current-password':'new-password'} minLength={authMode==='local'&&!hasVault&&!pendingImport?12:1} required/></label>
      {authMode==='local'&&!hasVault&&!pendingImport&&<label>Confirm password<input name="confirm" type="password" autoComplete="new-password" minLength={12} required/></label>}
      {error&&<p className="notice error" role="alert">{error}</p>}
      <button className="button gold full-width" disabled={busy}>{busy?'Unlocking…':authMode==='cloud'?'Sign in & edit':hasVault||pendingImport?'Unlock notebook':'Create encrypted notebook'}</button></form><small>{authMode==='local'?'Keep your password safe: it cannot be recovered. Clearing browser data removes the local notebook. Export backups regularly.':'Only the configured owner can save. Passwords are checked by Supabase Auth.'}</small></>:<><span className="eyebrow">A LITTLE DIVINE INSPIRATION</span><h2 id="dialog-title">Spell library</h2><p>Starter spells for the 2014 Paladin. Add them to your book, then mark your prepared spells.</p><input className="library-search" placeholder="Search spells…" aria-label="Search spells" value={query} onChange={e=>setQuery(e.target.value)}/><div className="library-list">{spellLibrary.filter(s=>(s.name+' '+s.description).toLowerCase().includes(query.toLowerCase())).map(s=><div key={s.id}><div><h3>{s.name}</h3><small>Level {s.level} · {s.casting}{s.concentration?' · Concentration':''}</small><p>{s.description}</p></div><button className="button outline" disabled={!editing||c.spells.some(v=>v.id===s.id)} onClick={()=>{change('spells',[...c.spells,clone(s)]);setStatus(`${s.name} added to your draft spellbook.`);}}>{c.spells.some(v=>v.id===s.id)?'Added':'Add'}</button></div>)}</div>{!editing&&<p className="panel-footnote">Unlock editing to add spells to Bob’s spellbook.</p>}</>}
    </dialog>
  </div>;
}
